(function(){
"use strict";
const TF={"5 Seconds":5,"15 Seconds":15,"30 Seconds":30,"1 Minute":60,"5 Minutes":300,"15 Minutes":900,"30 Minutes":1800,"1 Hour":3600,"4 Hours":14400,"12 Hours":43200,"1 Day":86400,"1 Week":604800,"1 Month":2592000,"6 Months":15552000,"1 Year":31536000};
const BYBIT={"1 Minute":"1","5 Minutes":"5","15 Minutes":"15","30 Minutes":"30","1 Hour":"60","4 Hours":"240","12 Hours":"720","1 Day":"D","1 Week":"W","1 Month":"M"};
const INDS=["Alligator","Fractals","EMA / SMA","Bollinger Bands","Parabolic SAR","Supertrend","Ichimoku Cloud","ADX","RSI","MACD","Stochastic","CCI","Williams %R","ATR","Keltner Channels","Donchian Channels","Support & Resistance","Horizontal Line"];
let chart,series,priceLine,ro,candles=[],tf=localStorage.getItem("gotradex_chart_timeframe")||"1 Minute",symbol=localStorage.getItem("gotradex_chart_symbol")||"BTCUSDT",ready=false,fastTimer,refreshTimer;
const active=new Set();
function addCss(){if(document.getElementById("gtx-v2-css"))return;const s=document.createElement("style");s.id="gtx-v2-css";s.textContent=\`
.gtx-v2{position:absolute!important;inset:0!important;background:#071827;display:flex;flex-direction:column;overflow:hidden}.gtxbar{height:40px;flex:0 0 40px;display:flex;align-items:center;gap:6px;padding:5px 7px;background:#081b31;border-bottom:1px solid #173553;overflow:auto;scrollbar-width:none}.gtxbar::-webkit-scrollbar{display:none}.gtxbtn{height:30px;flex:0 0 auto;border:1px solid #23466d;border-radius:7px;background:#102945;color:#dbe9f7;padding:0 9px;font-size:10px;font-weight:800}.gtxbtn:active{background:#176fca}.gtxsym{font-size:11px;font-weight:900;margin-right:auto;white-space:nowrap}.gtxstage{position:relative;flex:1;min-height:0}.gtxhost{position:absolute;inset:0}.gtxinfo{position:absolute;left:9px;top:9px;z-index:5;pointer-events:none}.gtxprice{font-size:14px;font-weight:900;text-shadow:0 1px 2px #000}.gtxmeta,.gtxsrc{font-size:8px;color:#8fa8c4;margin-top:2px}.gtxtools{position:absolute;right:8px;top:8px;z-index:10;display:flex;gap:5px}.gtxtools button{height:28px;border:1px solid #23466d;border-radius:7px;background:rgba(8,27,49,.94);color:#fff;font-size:9px;font-weight:800}.gtxmenu{display:none;position:absolute;right:8px;top:42px;width:min(310px,86vw);max-height:72%;overflow:auto;z-index:20;padding:9px;background:#081b31;border:1px solid #23466d;border-radius:10px;box-shadow:0 14px 35px rgba(0,0,0,.45)}.gtxmenu.open{display:block}.gtxmenu h4{margin:0 0 7px;font-size:11px;color:#fff}.gtxgrid{display:grid;grid-template-columns:1fr 1fr;gap:5px}.gtxgrid button{min-height:32px;border:1px solid #23466d;border-radius:7px;background:#102945;color:#dbe9f7;text-align:left;padding:6px 8px;font-size:9px}.gtxgrid button.on{background:#176fca;border-color:#176fca}.gtxload{position:absolute;inset:0;display:grid;place-items:center;background:rgba(7,24,39,.55);z-index:8;color:#8fa8c4;font-size:11px}.gtx-v2.ready .gtxload{display:none}.gtxstatus{position:absolute;left:9px;bottom:30px;z-index:5;font-size:8px;color:#66809d}@media(max-width:600px){.gtxbar{height:38px;flex-basis:38px}.gtxbtn{height:28px;font-size:9px}}
\`;document.head.appendChild(s)}
function root(){return document.querySelector(".chart")}
function rebuild(){const r=root();if(!r)return; r.innerHTML='<div class="gtxbar"><strong class="gtxsym" id="gtxSym">BTCUSDT</strong><button class="gtxbtn" id="gtxPrev">‹</button><button class="gtxbtn" id="gtxTf">1 Minute</button><button class="gtxbtn" id="gtxNext">›</button><button class="gtxbtn" id="gtxFit">FIT</button></div><div class="gtxstage"><div class="gtxhost" id="gtxHost"></div><div class="gtxinfo"><div class="gtxprice" id="gtxPrice">—</div><div class="gtxmeta" id="gtxMeta">—</div><div class="gtxsrc" id="gtxSrc">Loading…</div></div><div class="gtxtools"><button id="gtxInd">INDICATORS</button><button id="gtxType">CANDLES</button></div><div class="gtxmenu" id="gtxMenu"><h4>Indicators & chart tools</h4><div class="gtxgrid" id="gtxGrid"></div><button class="gtxbtn" id="gtxReset" style="width:100%;margin-top:7px">RESET INDICATORS</button></div><div class="gtxload">Building new chart engine…</div><div class="gtxstatus">Drag to scroll • pinch/ctrl-wheel to zoom • crosshair shows time/price</div></div>';r.className="chart gtx-v2"}
function sym(){let s=String(symbol||"BTCUSDT").toUpperCase().replace("/","");return s.endsWith("USDT")?s:s+"USDT"}
function price(v){v=Number(v);if(!Number.isFinite(v))return"—";return v>=1000?v.toFixed(2):v>=10?v.toFixed(4):v>=1?v.toFixed(5):v.toFixed(6)}
function time(t){return new Date(t*1000).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"})}
function dedupe(a){const m=new Map();a.forEach(x=>m.set(x.time,x));return[...m.values()].sort((a,b)=>a.time-b.time)}
function norm(a){return(Array.isArray(a)?a:[]).map(k=>({time:Math.floor(Number(k[0])/1000),open:+k[1],high:+k[2],low:+k[3],close:+k[4],volume:+(k[5]||0)})).filter(x=>Number.isFinite(x.time)&&Number.isFinite(x.close))}
async function liveData(){const iv=BYBIT[tf];if(!iv)return[];const r=await fetch("https://api.bybit.com/v5/market/kline?category=spot&symbol="+encodeURIComponent(sym())+"&interval="+iv+"&limit=500",{cache:"no-store"}),d=await r.json();if(!r.ok||+d?.retCode!==0)throw Error(d?.retMsg||"feed unavailable");return norm(d?.result?.list?.slice().reverse())}
function legacy(){const d=Array.isArray(window.demoCandleData)?window.demoCandleData:[],step=TF[tf]||60,now=Math.floor(Date.now()/1000);return d.slice(-500).map((x,i)=>({time:now-(d.length-1-i)*step,open:+x.open,high:+x.high,low:+x.low,close:+x.close,volume:+(x.volume||0)})).filter(x=>[x.open,x.high,x.low,x.close].every(Number.isFinite))}
function fallback(){let p=100,a=[],step=TF[tf]||60,now=Math.floor(Date.now()/1000);for(let i=0;i<250;i++){let o=p,c=Math.max(.001,o+(Math.sin(i*.55)+Math.cos(i*.21))*.3+(Math.random()-.5)*.7),h=Math.max(o,c)+Math.random()*.3,l=Math.min(o,c)-Math.random()*.3;a.push({time:now-(249-i)*step,open:o,high:h,low:l,close:c,volume:100});p=c}return a}
async function load(){try{candles=dedupe(await liveData());document.getElementById("gtxSrc").textContent="LIVE • Bybit market candles"}catch(e){candles=dedupe(legacy());document.getElementById("gtxSrc").textContent=candles.length?"DEMO FALLBACK • verified feed unavailable":"DEMO FALLBACK • chart engine ready";if(!candles.length)candles=fallback()}}
function addLine(d,c,w,t){const s=chart.addSeries(LightweightCharts.LineSeries,{color:c,lineWidth:w||1,priceLineVisible:false,lastValueVisible:false,title:t||"",crosshairMarkerVisible:false});s.setData(d);return s}
function sma(v,p){let q=[],o=[];v.forEach((x,i)=>{q.push(x);if(q.length>p)q.shift();if(q.length===p)o.push({time:candles[i].time,value:q.reduce((a,b)=>a+b,0)/p})});return o}
function ema(v,p){let o=[],k=2/(p+1),e=null;v.forEach((x,i)=>{e=e===null?x:x*k+e*(1-k);if(i>=p-1)o.push({time:candles[i].time,value:e})});return o}
function clearInd(){(window.__gtxV2Ind||[]).forEach(s=>{try{chart.removeSeries(s)}catch(e){}});window.__gtxV2Ind=[]}
function indicators(){clearInd();let c=candles.map(x=>x.close),h=candles.map(x=>x.high),l=candles.map(x=>x.low),a=[];if(active.has("EMA / SMA"))a.push(addLine(ema(c,9),"#f5c542",2,"EMA 9"),addLine(ema(c,21),"#5ea7ff",2,"EMA 21"));if(active.has("Alligator"))a.push(addLine(sma(c,5),"#57d68d",1,"Jaw"),addLine(sma(c,8),"#f5c542",1,"Teeth"),addLine(sma(c,13),"#ff6b6b",1,"Lips"));if(active.has("Bollinger Bands")){let m=sma(c,20),u=[],d=[];for(let i=19;i<c.length;i++){let q=c.slice(i-19,i+1),x=q.reduce((a,b)=>a+b,0)/20,sd=Math.sqrt(q.reduce((a,b)=>a+(b-x)**2,0)/20);u.push({time:candles[i].time,value:x+2*sd});d.push({time:candles[i].time,value:x-2*sd})}a.push(addLine(m,"#8fa8c4",1,"BB Mid"),addLine(u,"#9c7cff",1,"BB Upper"),addLine(d,"#9c7cff",1,"BB Lower"))}if(active.has("Donchian Channels")){let u=[],d=[];for(let i=19;i<c.length;i++){u.push({time:candles[i].time,value:Math.max(...h.slice(i-19,i+1))});d.push({time:candles[i].time,value:Math.min(...l.slice(i-19,i+1))})}a.push(addLine(u,"#a78bfa",1,"Donchian High"),addLine(d,"#a78bfa",1,"Donchian Low"))}if(active.has("Fractals")){let u=[],d=[];for(let i=2;i<c.length-2;i++){if(h[i]>h[i-1]&&h[i]>h[i-2]&&h[i]>h[i+1]&&h[i]>h[i+2])u.push({time:candles[i].time,value:h[i]});if(l[i]<l[i-1]&&l[i]<l[i-2]&&l[i]<l[i+1]&&l[i]<l[i+2])d.push({time:candles[i].time,value:l[i]})}a.push(addLine(u,"#ff9f43",2,"Fractal High"),addLine(d,"#48dbfb",2,"Fractal Low"))}window.__gtxV2Ind=a}
function build(){const host=document.getElementById("gtxHost");if(!host)return;if(chart)try{chart.remove()}catch(e){}chart=LightweightCharts.createChart(host,{autoSize:true,layout:{background:{type:"solid",color:"#071827"},textColor:"#8fa8c4",fontSize:10},grid:{vertLines:{color:"rgba(120,160,200,.08)"},horzLines:{color:"rgba(120,160,200,.08)"}},rightPriceScale:{visible:true,borderColor:"#23466d",scaleMargins:{top:.08,bottom:.12}},leftPriceScale:{visible:false},timeScale:{borderColor:"#23466d",timeVisible:true,secondsVisible:true,barSpacing:8,rightOffset:6,minBarSpacing:2,maxBarSpacing:32},crosshair:{mode:LightweightCharts.CrosshairMode.Normal},handleScroll:{mouseWheel:true,pressedMouseMove:true,horzTouchDrag:true},handleScale:{mouseWheel:true,pinch:true,axisPressedMouseMove:true}});series=chart.addSeries(LightweightCharts.CandlestickSeries,{upColor:"#36c275",downColor:"#e05b70",borderUpColor:"#36c275",borderDownColor:"#e05b70",wickUpColor:"#36c275",wickDownColor:"#e05b70",priceLineVisible:false});series.setData(candles);priceLine=series.createPriceLine({price:candles.at(-1).close,color:"#f5c542",lineWidth:1,lineStyle:2,axisLabelVisible:true,title:"LIVE"});indicators();chart.timeScale().fitContent();document.querySelector(".gtx-v2")?.classList.add("ready");ro?.disconnect();ro=new ResizeObserver(()=>chart?.resize(host.clientWidth,host.clientHeight));ro.observe(host);paint()}
function paint(){let x=candles.at(-1);if(!x)return;document.getElementById("gtxPrice").textContent=price(x.close);document.getElementById("gtxMeta").textContent="O "+price(x.open)+"  H "+price(x.high)+"  L "+price(x.low)+"  C "+price(x.close)+" • "+time(x.time);document.getElementById("gtxSym").textContent=sym()+" • "+tf;priceLine?.applyOptions({price:x.close})}
async function refresh(){await load();if(!chart)build();else{series.setData(candles);indicators();priceLine?.applyOptions({price:candles.at(-1).close});paint()}}
async function fast(){if(!ready||!["5 Seconds","15 Seconds","30 Seconds"].includes(tf)||!candles.length)return;try{let r=await fetch("https://api.bybit.com/v5/market/tickers?category=spot&symbol="+encodeURIComponent(sym()),{cache:"no-store"}),d=await r.json(),p=+d?.result?.list?.[0]?.lastPrice;if(!Number.isFinite(p))return;let step=TF[tf],t=Math.floor(Date.now()/1000/step)*step,x=candles.at(-1);if(!x||t>x.time){x={time:t,open:p,high:p,low:p,close:p,volume:0};candles.push(x);candles=candles.slice(-500)}else{x.close=p;x.high=Math.max(x.high,p);x.low=Math.min(x.low,p)}series?.update(x);priceLine?.applyOptions({price:p});paint()}catch(e){}}
function controls(){const order=Object.keys(TF),prev=document.getElementById("gtxPrev"),next=document.getElementById("gtxNext"),tfb=document.getElementById("gtxTf");const move=d=>{let i=order.indexOf(tf);tf=order[(i+d+order.length)%order.length];localStorage.setItem("gotradex_chart_timeframe",tf);tfb.textContent=tf;refresh()};prev.onclick=()=>move(-1);next.onclick=()=>move(1);tfb.onclick=()=>move(1);document.getElementById("gtxFit").onclick=()=>chart?.timeScale().fitContent();document.getElementById("gtxInd").onclick=()=>document.getElementById("gtxMenu").classList.toggle("open");document.getElementById("gtxReset").onclick=()=>{active.clear();renderInd();indicators()};document.getElementById("gtxType").onclick=()=>{let b=document.getElementById("gtxType"),line=b.dataset.line==="1";b.dataset.line=line?"0":"1";b.textContent=line?"CANDLES":"LINE";chart.removeSeries(series);series=line?chart.addSeries(LightweightCharts.LineSeries,{color:"#4f9cff",lineWidth:2,priceLineVisible:false}):chart.addSeries(LightweightCharts.CandlestickSeries,{upColor:"#36c275",downColor:"#e05b70",borderUpColor:"#36c275",borderDownColor:"#e05b70",wickUpColor:"#36c275",wickDownColor:"#e05b70",priceLineVisible:false});series.setData(line?candles.map(x=>({time:x.time,value:x.close})):candles);priceLine=series.createPriceLine({price:candles.at(-1).close,color:"#f5c542",lineWidth:1,lineStyle:2,axisLabelVisible:true,title:"LIVE"});indicators()};let g=document.getElementById("gtxGrid");INDS.forEach(n=>{let b=document.createElement("button");b.textContent=n;b.dataset.i=n;b.onclick=()=>{active.has(n)?active.delete(n):active.add(n);renderInd();indicators()};g.appendChild(b)});renderInd()}
function renderInd(){document.querySelectorAll("#gtxGrid button").forEach(b=>b.classList.toggle("on",active.has(b.dataset.i)))}
function removeLegacy(){document.querySelectorAll(".kenkleyWrap,#kenkleyToggle,#kenkleySettings,.kenkleySettings,[data-tool='Kenkley’s Lines'],[data-tool=\"Kenkley's Lines\"]").forEach(e=>e.remove())}
async function boot(){if(ready||!root())return;ready=true;addCss();removeLegacy();rebuild();const s=document.createElement("script");s.src="https://unpkg.com/lightweight-charts@5.2.0/dist/lightweight-charts.standalone.production.js";s.async=true;s.onload=async()=>{controls();await refresh();clearInterval(refreshTimer);refreshTimer=setInterval(refresh,15000);clearInterval(fastTimer);fastTimer=setInterval(fast,1000)};s.onerror=()=>{document.getElementById("gtxSrc").textContent="Chart library failed to load"};document.head.appendChild(s)}
window.GoTradeXChartEngine={boot,refresh,setSymbol:x=>{symbol=String(x||"BTCUSDT").toUpperCase();localStorage.setItem("gotradex_chart_symbol",symbol);refresh()},setTimeframe:x=>{if(TF[x]){tf=x;localStorage.setItem("gotradex_chart_timeframe",tf);document.getElementById("gtxTf").textContent=tf;refresh()}}};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else setTimeout(boot,0);
})();