(function(){
"use strict";
const TF={"5 Seconds":5,"15 Seconds":15,"30 Seconds":30,"1 Minute":60,"5 Minutes":300,"15 Minutes":900,"30 Minutes":1800,"1 Hour":3600,"4 Hours":14400,"12 Hours":43200,"1 Day":86400,"1 Week":604800,"1 Month":2592000,"6 Months":15552000,"1 Year":31536000};
const BYBIT={"1 Minute":"1","5 Minutes":"5","15 Minutes":"15","30 Minutes":"30","1 Hour":"60","4 Hours":"240","12 Hours":"720","1 Day":"D","1 Week":"W","1 Month":"M"};
const INDS=["Alligator","Fractals","EMA / SMA","Bollinger Bands","Parabolic SAR","Supertrend","Ichimoku Cloud","ADX","RSI","MACD","Stochastic","CCI","Williams %R","ATR","Keltner Channels","Donchian Channels","Support & Resistance","Horizontal Line"];
let chart,series,priceLine,ro,candles=[],tf=localStorage.getItem("gotradex_chart_timeframe")||"1 Minute",symbol=localStorage.getItem("gotradex_chart_symbol")||"BTCUSDT",ready=false,fastTimer,refreshTimer;
const active=new Set();
function addCss(){if(document.getElementById("gtx-v2-css"))return;const s=document.createElement("style");s.id="gtx-v2-css";s.textContent=\`
.gtx-v2{position:absolute!important;inset:0!important;background:#071827;display:flex;flex-direction:column;overflow:hidden;min-height:420px}.gtxbar{height:44px;flex:0 0 44px;display:flex;align-items:center;gap:7px;padding:6px 9px;background:#081b31;border-bottom:1px solid #23466d;overflow:auto;scrollbar-width:none}.gtxbar::-webkit-scrollbar{display:none}.gtxbtn{height:32px;min-width:42px;flex:0 0 auto;border:1px solid #2b527d;border-radius:7px;background:#102945;color:#dbe9f7;padding:0 10px;font-size:10px;font-weight:800}.gtxbtn:hover,.gtxbtn:focus{background:#176fca;color:#fff}.gtxsym{font-size:12px;font-weight:900;margin-right:auto;white-space:nowrap;color:#fff}.gtxstage{position:relative;flex:1;min-height:360px}.gtxbar{height:40px;flex:0 0 40px;display:flex;align-items:center;gap:6px;padding:5px 7px;background:#081b31;border-bottom:1px solid #173553;overflow:auto;scrollbar-width:none}.gtxbar::-webkit-scrollbar{display:none}.gtxbtn{height:30px;flex:0 0 auto;border:1px solid #23466d;border-radius:7px;background:#102945;color:#dbe9f7;padding:0 9px;font-size:10px;font-weight:800}.gtxbtn:active{background:#176fca}.gtxsym{font-size:11px;font-weight:900;margin-right:auto;white-space:nowrap}.gtxstage{position:relative;flex:1;min-height:0}.gtxhost{position:absolute;inset:0;min-height:360px}.gtxhost canvas{touch-action:none!important}.gtxinfo{position:absolute;left:9px;top:9px;z-index:5;pointer-events:none}.gtxprice{font-size:17px;line-height:20px;font-weight:900;text-shadow:0 1px 2px #000;color:#fff}.gtxmeta,.gtxsrc{font-size:9px;color:#a8bfd7;margin-top:3px}.gtxmeta,.gtxsrc{font-size:8px;color:#8fa8c4;margin-top:2px}.gtxtools{position:absolute;right:10px;top:10px;z-index:10;display:flex;gap:6px}.gtxtools button{height:31px;border:1px solid #2b527d;border-radius:7px;background:rgba(8,27,49,.96);color:#fff;font-size:9px;font-weight:900;padding:0 10px}.gtxmenu{display:none;position:absolute;right:10px;top:48px;width:min(340px,88vw);max-height:76%;overflow:auto;z-index:20;padding:10px;background:#081b31;border:1px solid #2b527d;border-radius:10px;box-shadow:0 14px 35px rgba(0,0,0,.5)}.gtxmenu.open{display:block}.gtxmenu h4{margin:0 0 7px;font-size:11px;color:#fff}.gtxgrid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.gtxgrid button{min-height:34px;border:1px solid #2b527d;border-radius:7px;background:#102945;color:#dbe9f7;text-align:left;padding:7px 8px;font-size:9px}.gtxgrid button.on{background:#176fca;border-color:#176fca}.gtxload{position:absolute;inset:0;display:grid;place-items:center;background:rgba(7,24,39,.72);z-index:30;color:#a8bfd7;font-size:12px;font-weight:700}.gtx-v2.ready .gtxload{display:none}.gtxstatus{position:absolute;left:9px;bottom:30px;z-index:5;font-size:8px;color:#66809d}@media(max-width:700px){.gtxbar{height:42px;flex-basis:42px}.gtxstage,.gtxhost{min-height:430px}.gtxbtn{height:30px;font-size:9px}.gtxprice{font-size:15px}}.gtxbtn{height:28px;font-size:9px}}
\`;document.head.appendChild(s)}
function root(){return document.querySelector(".chart")}
function rebuild(){const r=root();if(!r)return; r.innerHTML='<div class="gtxbar"><strong class="gtxsym" id="gtxSym">BTCUSDT</strong><button class="gtxbtn" id="gtxPrev">‹</button><button class="gtxbtn" id="gtxTf">1 Minute</button><button class="gtxbtn" id="gtxNext">›</button><button class="gtxbtn" id="gtxFit">FIT</button></div><div class="gtxstage"><div class="gtxhost" id="gtxHost"></div><div class="gtxinfo"><div class="gtxprice" id="gtxPrice">—</div><div class="gtxmeta" id="gtxMeta">—</div><div class="gtxsrc" id="gtxSrc">Loading…</div></div><div class="gtxtools"><button id="gtxInd">INDICATORS</button><button id="gtxType">CANDLES</button></div><div class="gtxmenu" id="gtxMenu"><h4>Indicators & chart tools</h4><div class="gtxgrid" id="gtxGrid"></div><button class="gtxbtn" id="gtxReset" style="width:100%;margin-top:7px">RESET INDICATORS</button></div><div class="gtxload">Building new chart engine…</div><div class="gtxstatus">Drag to scroll • pinch/ctrl-wheel to zoom • crosshair shows time/price</div></div>';r.className="chart gtx-v2"}
function sym(){let s=String(symbol||"BTCUSDT").toUpperCase().replace("/","");return s.endsWith("USDT")?s:s+"USDT"}
function price(v){v=Number(v);if(!Number.isFinite(v))return"—";return v>=1000?v.toFixed(2):v>=10?v.toFixed(4):v>=1?v.toFixed(5):v.toFixed(6)}
function time(t){return new Date(t*1000).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"})}
function dedupe(a){const m=new Map();a.forEach(x=>m.set(x.time,x));return[...m.values()].sort((a,b)=>a.time-b.time)}
function norm(a){return(Array.isArray(a)?a:[]).map(k=>({time:Math.floor(Number(k[0])/1000),open:+k[1],high:+k[2],low:+k[3],close:+k[4],volume:+(k[5]||0)})).filter(x=>Number.isFinite(x.time)&&Number.isFinite(x.close))}
async function liveData(){const iv=BYBIT[tf];if(!iv)return[];const r=await fetch("https://api.bybit.com/v5/market/kline?category=spot&symbol="+encodeURIComponent(sym())+"&interval="+iv+"&limit=500",{cache:"no-store"}),d=await r.json();if(!r.ok||+d?.retCode!==0)throw Error(d?.retMsg||"feed unavailable");return norm(d?.result?.list?.slice().reverse())}
function legacy(){const d=Array.isArray(window.demoCandleData)?window.demoCandleData:[],step=TF[tf]||60,now=Math.floor(Date.now()/1000);return d.slice(-500).map((x,i)=>({time:now-(d.length-1-i)*step,open:+x.open,high:+x.high,low:+x.low,close:+x.close,volume:+(x.volume||0)})).filter(x=>[x.open,x.high,x.low,x.close].every(Number.isFinite))}
function fallback(){let p=100,a=[],step=TF[tf]||60,now=Math.floor(Date.now()/1000);for(let i=0;i<250;i++){let o=p,c=Math.max(.001,o+(Math.sin(i*.55)+Math.cos(i*.21))*.3+(Math.random()-.5)*.7),h=Math.max(o,c)+Math.random()*.3,l=Math.min(o,c)-Math.random()*.3;a.push({time:now-(249-i)*step,open:o,high:h,low:l,close:c,volume:100});p=c}return a}
async function load(){try{candles=dedupe(await liveData());document.getElementById("gtxSrc").textContent="LIVE • Bybit market candles"}catch(e){candles=dedupe(legacy());document.getElementById("gtxSrc").textContent=candles.length?"DEMO FALLBACK • verified feed unavailable":"DEMO FALLBACK • chart engine ready";if(!candles.length)candles=fallback()}candles=candles.slice(-500)})();