const C=window.GOTRADEX_CONFIG||{};const SB=window.supabase?.createClient(C.SUPABASE_URL,C.SUPABASE_KEY);const $=id=>document.getElementById(id);
const state={user:null,page:"dashboard",symbol:"BTCUSDT",tf:"1h",prices:{},candles:[],chart:null,bot:false,timer:null,trades:[],balance:10000,signals:[],webhook:localStorage.getItem("gotradex_webhook")||""};
const symbols=["BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT"];
const titles={dashboard:["Dashboard","Live market data, signals and automated paper execution."],markets:["Markets","Live crypto prices from Binance public market data."],signals:["AI Signals","Technical analysis from live candles."],portfolio:["Portfolio","Paper positions and trade history."],bot:["AutoBot","Automated paper-trading engine."],settings:["Settings","Account and connection settings."]};
function msg(t,type=""){const e=$("auth-message");e.textContent=t;e.className="message "+type}
function showAuth(mode="login"){const signup=mode==="signup";$("auth-title").textContent=signup?"Create your account":"Welcome back";$("auth-subtitle").textContent=signup?"Create a secure GoTradeX account.":"Sign in to your trading dashboard.";$("auth-submit").textContent=signup?"Create account":"Log in";$("switch-auth").textContent=signup?"Back to login":"Create account";$("signup-extra").classList.toggle("hidden",!signup);$("terms-row").classList.toggle("hidden",!signup);$("auth-form").dataset.mode=mode;msg("")}
async function authSubmit(e){e.preventDefault();const email=$("auth-email").value.trim();const password=$("auth-password").value;if(!email||password.length<6)return msg("Enter a valid email and a password of at least 6 characters.","error");$("auth-submit").disabled=true;msg("Connecting…");try{if($("auth-form").dataset.mode==="signup"){if(!$("signup-terms").checked)return msg("Please accept the terms.","error");const name=$("signup-name").value.trim();const r=await SB.auth.signUp({email,password,options:{data:{name}}});if(r.error)throw r.error;if(!r.data.session){msg("Account created. Check your email to confirm it, then log in.","success");showAuth("login")}else await openApp(r.data.session.user)}else{const r=await SB.auth.signInWithPassword({email,password});if(r.error)throw r.error;await openApp(r.data.session.user)}}catch(err){console.error(err);msg(err.message||"Authentication failed.","error")}finally{$("auth-submit").disabled=false}}
async function resetPassword(){const email=prompt("Enter your GoTradeX email:");if(!email)return;const r=await SB.auth.resetPasswordForEmail(email.trim(),{redirectTo:location.origin+location.pathname});if(r.error)msg(r.error.message,"error");else msg("Password reset email sent.","success")}
async function openApp(user){state.user=user;$("auth").classList.add("hidden");$("app").classList.remove("hidden");$("loader").style.display="none";$("user-name").textContent=user.user_metadata?.name||user.email.split("@")[0];$("profile-name").value=user.user_metadata?.name||"";$("profile-email").value=user.email||"";$("supabase-status").textContent="Supabase: connected";go("dashboard");await refreshAll();startLive()}
async function logout(){if(SB)await SB.auth.signOut();stopBot();location.reload()}
function go(page){state.page=page;document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));$("page-"+page).classList.add("active");document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.page===page));$("page-title").textContent=titles[page][0];$("page-subtitle").textContent=titles[page][1]}
async function api(path){const r=await fetch("https://api.binance.com"+path);if(!r.ok)throw Error("Market API "+r.status);return r.json()}
async function refreshAll(){try{const rows=await Promise.all(symbols.map(async s=>[s,await api("/api/v3/ticker/24hr?symbol="+s)]));rows.forEach(([s,d])=>state.prices[s]={price:+d.lastPrice,change:+d.priceChangePercent});$("connection").textContent="LIVE";$("connection").classList.add("online");renderMarkets();renderStats();await loadCandles(state.symbol,state.tf)}catch(e){console.error(e);$("connection").textContent="Market error";}}
function renderMarkets(filter=""){const list=symbols.filter(s=>s.includes(filter.toUpperCase()));const html=list.map(s=>{const d=state.prices[s]||{};const c=(d.change||0)>=0?"up":"down";return '<div class="market-row" data-symbol="'+s+'"><div><b>'+s+'</b><small>Binance spot</small></div><div><b>$'+fmt(d.price)+'</b><small class="'+c+'">'+(d.change||0).toFixed(2)+'%</small></div></div>'}).join("");$("market-list").innerHTML=html||'<div class="empty">No markets found.</div>';$("markets-full").innerHTML=list.map(s=>{const d=state.prices[s]||{};return '<div class="market-card" data-symbol="'+s+'"><h3>'+s+'</h3><p>Live Binance market</p><b>$'+fmt(d.price)+'</b> <span class="'+((d.change||0)>=0?"up":"down")+'">'+(d.change||0).toFixed(2)+'%</span></div>'}).join("");document.querySelectorAll("[data-symbol]").forEach(e=>e.onclick=()=>selectSymbol(e.dataset.symbol))}
function renderStats(){$("balance").textContent="$"+state.balance.toFixed(2);$("equity").textContent="$"+state.balance.toFixed(2);$("positions").textContent=String(state.trades.filter(t=>t.open).length);$("bot-status").textContent=state.bot?"ON":"OFF"}
function fmt(n){return Number.isFinite(n)?n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):"—"}
async function selectSymbol(s){state.symbol=s;await loadCandles(s,state.tf);go("dashboard")}
async function loadCandles(s,tf){try{const d=await api("/api/v3/klines?symbol="+s+"&interval="+tf+"&limit=100");state.candles=d.map(x=>({t:x[0],c:+x[4]}));$("chart-symbol").textContent=s;$("chart-price").textContent="$"+fmt(state.candles.at(-1)?.c);drawChart()}catch(e){console.error(e)}}
function drawChart(){const ctx=$("chart");if(state.chart)state.chart.destroy();state.chart=new Chart(ctx,{type:"line",data:{labels:state.candles.map(x=>new Date(x.t).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})),datasets:[{data:state.candles.map(x=>x.c),borderColor:"#3b82f6",backgroundColor:"#3b82f622",fill:true,tension:.25,pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{display:false},y:{grid:{color:"#20334d"},ticks:{color:"#91a3bb"}}}}})}
async function analyze(){await loadCandles(state.symbol,state.tf);const a=state.candles.map(x=>x.c);if(a.length<30)return;const ema=(arr,n)=>{let k=2/(n+1),v=arr.slice(0,n).reduce((x,y)=>x+y,0)/n;for(let i=n;i<arr.length;i++)v=arr[i]*k+v*(1-k);return v};const e9=ema(a,9),e21=ema(a,21);let gains=0,loss=0;for(let i=a.length-14;i<a.length;i++){const d=a[i]-a[i-1];if(d>=0)gains+=d;else loss-=d}const rs=loss?gains/loss:99,rsi=100-100/(1+rs);const dir=e9>e21&&rsi<70?"BUY":e9<e21&&rsi>30?"SELL":"WAIT";const confidence=Math.min(95,Math.round(55+Math.abs(e9-e21)/a.at(-1)*1000+Math.abs(rsi-50)));const s={time:new Date().toLocaleTimeString(),symbol:state.symbol,direction:dir,confidence};state.signals.unshift(s);state.signals=state.signals.slice(0,20);$("signal-box").innerHTML='<span>'+dir+'</span><b>Confidence '+confidence+'% · RSI '+rsi.toFixed(1)+'</b>';renderSignals();if(state.bot&&confidence>=Number($("bot-confidence").value))paperTrade(dir,confidence)}
function renderSignals(){$("signals").innerHTML=state.signals.map(s=>'<div class="market-row"><b>'+s.symbol+' · '+s.direction+'</b><small>'+s.confidence+'% · '+s.time+'</small></div>').join("")||'<div class="empty">No signals yet.</div>'}
function paperTrade(dir,confidence){if(dir==="WAIT")return;state.trades.unshift({time:new Date().toLocaleString(),symbol:state.symbol,side:dir,confidence,open:false});renderTrades();renderStats();log("Paper signal executed: "+dir+" "+state.symbol+" ("+confidence+"%).")}
function renderTrades(){$("trades").innerHTML=state.trades.map(t=>'<div class="trades-row"><span>'+t.time+'</span><span>'+t.symbol+'</span><span>'+t.side+'</span><span>'+t.confidence+'%</span></div>').join("")||'<div class="empty">No paper trades yet.</div>'}
function log(t){$("bot-log").textContent=new Date().toLocaleTimeString()+" — "+t+"\n"+$("bot-log").textContent}
function startBot(){if(state.bot)return;state.bot=true;$("bot-toggle").textContent="Stop AutoBot";renderStats();log("AutoBot started in PAPER mode.");state.timer=setInterval(()=>analyze().catch(console.error),60000)}
function stopBot(){state.bot=false;if(state.timer)clearInterval(state.timer);state.timer=null;if($("bot-toggle"))$("bot-toggle").textContent="Start AutoBot";renderStats()}
async function saveWebhook(){state.webhook=$("webhook").value.trim();localStorage.setItem("gotradex_webhook",state.webhook);if(state.webhook)await sendWebhook({type:"settings_saved"});log("Automation webhook saved.")}
async function sendWebhook(payload){if(!state.webhook)return;try{const r=await fetch(state.webhook,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({source:"GoTradeX",...payload,timestamp:new Date().toISOString()})});if(!r.ok)throw Error("HTTP "+r.status);log("Latenode webhook delivered.")}catch(e){log("Webhook error: "+e.message)}}
async function saveProfile(){const name=$("profile-name").value.trim();const r=await SB.auth.updateUser({data:{name}});if(r.error)alert(r.error.message);else{$("user-name").textContent=name||state.user.email.split("@")[0];alert("Profile saved.")}}
async function changePassword(){const p=prompt("New password (minimum 6 characters):");if(!p)return;if(p.length<6)return alert("Password must be at least 6 characters.");const r=await SB.auth.updateUser({password:p});alert(r.error?r.error.message:"Password changed successfully.")}
function startLive(){setInterval(()=>{if(!state.user)return;refreshAll().catch(console.error)},30000)}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>go(b.dataset.page));$("auth-form").onsubmit=authSubmit;$("switch-auth").onclick=()=>showAuth($("auth-form").dataset.mode==="signup"?"login":"signup");$("forgot-btn").onclick=resetPassword;$("forgot-settings").onclick=resetPassword;$("logout").onclick=logout;$("password-toggle").onclick=()=>{const i=$("auth-password");i.type=i.type==="password"?"text":"password";$("password-toggle").textContent=i.type==="password"?"Show":"Hide"};$("refresh").onclick=()=>refreshAll();$("search").oninput=e=>renderMarkets(e.target.value);$("analyze").onclick=()=>analyze().catch(console.error);$("reset-paper").onclick=()=>{state.trades=[];state.balance=10000;renderTrades();renderStats()};$("bot-toggle").onclick=()=>state.bot?stopBot():startBot();$("save-settings").onclick=saveWebhook;$("test-webhook").onclick=()=>sendWebhook({type:"test",message:"GoTradeX connection test"});$("save-profile").onclick=saveProfile;$("change-password").onclick=changePassword;document.querySelectorAll("#timeframes button").forEach(b=>b.onclick=async()=>{state.tf=b.dataset.tf;document.querySelectorAll("#timeframes button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");await loadCandles(state.symbol,state.tf)});
$("webhook").value=state.webhook;
(async()=>{try{const r=await SB.auth.getSession();if(r.data.session)await openApp(r.data.session.user);else{$("loader").style.display="none";showAuth("login")}}catch(e){console.error(e);$("loader").style.display="none";showAuth("login")}})();
SB.auth.onAuthStateChange((event,session)=>{if(event==="SIGNED_OUT")location.reload()});
